---
# tasks file for master
- name: Make the Swap inactive
  command: swapoff -a

- name: Remove Swap entry from /etc/fstab.
  lineinfile:
     dest: /etc/fstab
     regexp: swap
     state: absent

- name: "installation of apt-transport"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - vim
      - software-properties-common
      - iproute2
    state: present
    update_cache: true

- name: create Docker config directory
  file: path=/etc/docker state=directory

- name: changing Docker to systemd driver
  copy:
    dest: "/etc/docker/daemon.json"
    content: |
        {
        "exec-opts": ["native.cgroupdriver=systemd"]
        }

- name: "systemctl"
  shell: "sysctl --system"

- name: Add Docker’s official GPG key
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker
  apt:
    name:
       - docker-ce
       - docker-ce-cli
       - containerd.io
    state: present
    update_cache: true

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Kubenetes repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'
    mode: 0600

- name: installation of kubeadm,kubectl,kubelet
  apt:
    name:
    - kubeadm
    - kubectl
    - kubelet
    state: present
    update_cache: true


- name: "pulling k8s master programs"
  command: "kubeadm config images pull"
  changed_when: false

- name: Enable service docker, and enable persistently
  service:
     name: "{{ item }}"
     state: started
     enabled: true
  loop: "{{ service_names }}"

- name: Initializing k8s cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem

- name: Create directory for jenkins kube config
  file:
    path: /home/jenkins/.kube
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Copy /etc/kubernetes/admin.conf to user home directory /home/jenkins/.kube/config.
  become_user: root
  become_method: sudo
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/jenkins/.kube/config
    remote_src: yes
    owner: jenkins
    group: jenkins
    mode: '0644'

- pause: seconds=10

- name: Remove the cache directory
  file:
    path: /home/jenkins/.kube/cache
    state: absent

- name: Setting up kubectl on Master Node
  shell:
    cmd: |
       sudo mkdir -p $HOME/.kube
       sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
       sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Deploying Flannel on Master Node
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Creating token for Slave
  command: kubeadm token create  --print-join-command
  register: token

- debug:
    msg: " {{ token.stdout }}"

- name: copy join command to local file
  become: false
  local_action: copy content="{{ token.stdout[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches
